import { useEffect, useMemo, useState, type FormEvent } from "react";
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, Timestamp, updateDoc } from "firebase/firestore";
import { db } from "./firebase";
import "./SportsAdmin.css";

type MatchStatus = "scheduled" | "finished" | "postponed" | "cancelled";
type Match = { id:string; teamId:string; teamName:string; competitionName:string; homeTeam:string; awayTeam:string; kickoffAt:Date; venue:string; status:MatchStatus; homeScore:number|null; awayScore:number|null; active:boolean };
type Props = { onBack:()=>void };
const TEAMS = ["Kampfmannschaft","Challenge","U17","U12","U10","U8"];

export default function MatchAdmin({onBack}:Props){
 const [matches,setMatches]=useState<Match[]>([]); const [editing,setEditing]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const empty={teamName:"Kampfmannschaft",competitionName:"1. Klasse A",homeTeam:"TSU Ainet",awayTeam:"",date:"",time:"17:00",venue:"Sandgrubenstadion Ainet",status:"scheduled" as MatchStatus,homeScore:"",awayScore:"",active:true};
 const [form,setForm]=useState(empty);
 useEffect(()=>onSnapshot(query(collection(db,"kfvMatches"),orderBy("kickoffAt","asc")),snap=>setMatches(snap.docs.map(d=>{const x=d.data(); return {id:d.id,teamId:String(x.teamId??""),teamName:String(x.teamName??""),competitionName:String(x.competitionName??""),homeTeam:String(x.homeTeam??""),awayTeam:String(x.awayTeam??""),kickoffAt:x.kickoffAt instanceof Timestamp?x.kickoffAt.toDate():new Date(),venue:String(x.venue??""),status:(x.status??"scheduled") as MatchStatus,homeScore:typeof x.homeScore==="number"?x.homeScore:null,awayScore:typeof x.awayScore==="number"?x.awayScore:null,active:x.active!==false}}))),[]);
 const future=useMemo(()=>matches.filter(m=>m.kickoffAt>=new Date()).length,[matches]);
 function reset(){setEditing(null);setForm(empty)}
 function edit(m:Match){ const dt=m.kickoffAt; setEditing(m.id); setForm({teamName:m.teamName,competitionName:m.competitionName,homeTeam:m.homeTeam,awayTeam:m.awayTeam,date:dt.toISOString().slice(0,10),time:dt.toTimeString().slice(0,5),venue:m.venue,status:m.status,homeScore:m.homeScore===null?"":String(m.homeScore),awayScore:m.awayScore===null?"":String(m.awayScore),active:m.active}); window.scrollTo({top:0,behavior:"smooth"}) }
 async function submit(e:FormEvent){e.preventDefault(); if(!form.awayTeam||!form.date){setMessage("Bitte Gegner und Datum eintragen.");return} setSaving(true); const kickoffAt=Timestamp.fromDate(new Date(`${form.date}T${form.time}:00`)); const teamId=form.teamName.toLowerCase().replaceAll(" ","-"); const payload={teamId,teamName:form.teamName,competitionName:form.competitionName.trim(),homeTeam:form.homeTeam.trim(),awayTeam:form.awayTeam.trim(),kickoffAt,venue:form.venue.trim(),status:form.status,homeScore:form.homeScore===""?null:Number(form.homeScore),awayScore:form.awayScore===""?null:Number(form.awayScore),active:form.active,source:"manual",sourceUpdatedAt:serverTimestamp(),updatedAt:serverTimestamp()}; try{editing?await updateDoc(doc(db,"kfvMatches",editing),payload):await addDoc(collection(db,"kfvMatches"),{...payload,createdAt:serverTimestamp()}); setMessage("Spiel gespeichert.");reset()}catch{setMessage("Speichern fehlgeschlagen. Prüfe die Firestore-Regeln.")}finally{setSaving(false)}}
 return <section className="sports-admin"><button className="admin-back" onClick={onBack}>← Zurück</button><header><p>TSU Ainet · Firestore</p><h2>Spiele verwalten</h2><span>{matches.length} Spiele · {future} kommende</span></header>
 <form onSubmit={submit} className="sports-form"><label>Mannschaft<select value={form.teamName} onChange={e=>setForm({...form,teamName:e.target.value})}>{TEAMS.map(t=><option key={t}>{t}</option>)}</select></label><label>Bewerb<input value={form.competitionName} onChange={e=>setForm({...form,competitionName:e.target.value})}/></label><label>Heim<input value={form.homeTeam} onChange={e=>setForm({...form,homeTeam:e.target.value})}/></label><label>Auswärts<input value={form.awayTeam} onChange={e=>setForm({...form,awayTeam:e.target.value})}/></label><label>Datum<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Uhrzeit<input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>Spielort<input value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as MatchStatus})}><option value="scheduled">Angesetzt</option><option value="finished">Beendet</option><option value="postponed">Verschoben</option><option value="cancelled">Abgesagt</option></select></label><label>Heimtore<input type="number" min="0" value={form.homeScore} onChange={e=>setForm({...form,homeScore:e.target.value})}/></label><label>Auswärtstore<input type="number" min="0" value={form.awayScore} onChange={e=>setForm({...form,awayScore:e.target.value})}/></label><div className="form-actions"><button disabled={saving}>{saving?"Speichert…":editing?"Änderungen speichern":"Spiel anlegen"}</button>{editing&&<button type="button" className="secondary" onClick={reset}>Abbrechen</button>}</div></form>{message&&<p className="admin-message">{message}</p>}
 <div className="admin-list">{matches.map(m=><article key={m.id}><div><small>{m.teamName} · {m.competitionName}</small><strong>{m.homeTeam} – {m.awayTeam}</strong><span>{m.kickoffAt.toLocaleString("de-AT",{dateStyle:"medium",timeStyle:"short"})} · {m.venue}</span></div><b>{m.homeScore===null?"–":`${m.homeScore}:${m.awayScore}`}</b><button onClick={()=>edit(m)}>Bearbeiten</button><button className="danger" onClick={()=>confirm("Spiel wirklich löschen?")&&deleteDoc(doc(db,"kfvMatches",m.id))}>Löschen</button></article>)}</div></section>
}
