import { useEffect, useState, type FormEvent } from "react";
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from "firebase/firestore";
import { db } from "./firebase";
import "./SportsAdmin.css";
type Row={id:string;teamName:string;competitionName:string;position:number;clubName:string;played:number;won:number;drawn:number;lost:number;goalsFor:number;goalsAgainst:number;points:number;active:boolean}; type Props={onBack:()=>void}; const TEAMS=["Kampfmannschaft","Challenge","U17","U12","U10","U8"];
export default function StandingsAdmin({onBack}:Props){const [rows,setRows]=useState<Row[]>([]);const [editing,setEditing]=useState<string|null>(null);const empty={teamName:"Kampfmannschaft",competitionName:"1. Klasse A",position:"1",clubName:"TSU Ainet",played:"0",won:"0",drawn:"0",lost:"0",goalsFor:"0",goalsAgainst:"0",points:"0",active:true};const [form,setForm]=useState(empty);const [msg,setMsg]=useState("");
useEffect(()=>onSnapshot(query(collection(db,"kfvStandings"),orderBy("position","asc")),s=>setRows(s.docs.map(d=>({id:d.id,...d.data()} as Row)))),[]);
function reset(){setEditing(null);setForm(empty)} function edit(r:Row){setEditing(r.id);setForm({teamName:r.teamName,competitionName:r.competitionName,position:String(r.position),clubName:r.clubName,played:String(r.played),won:String(r.won),drawn:String(r.drawn),lost:String(r.lost),goalsFor:String(r.goalsFor),goalsAgainst:String(r.goalsAgainst),points:String(r.points),active:r.active});window.scrollTo({top:0,behavior:"smooth"})}
async function submit(e:FormEvent){e.preventDefault();const n=(v:string)=>Number(v)||0;const payload={teamId:form.teamName.toLowerCase().replaceAll(" ","-"),teamName:form.teamName,competitionName:form.competitionName.trim(),position:n(form.position),clubName:form.clubName.trim(),played:n(form.played),won:n(form.won),drawn:n(form.drawn),lost:n(form.lost),goalsFor:n(form.goalsFor),goalsAgainst:n(form.goalsAgainst),goalDifference:n(form.goalsFor)-n(form.goalsAgainst),points:n(form.points),active:form.active,source:"manual",updatedAt:serverTimestamp()};try{editing?await updateDoc(doc(db,"kfvStandings",editing),payload):await addDoc(collection(db,"kfvStandings"),{...payload,createdAt:serverTimestamp()});setMsg("Tabellenzeile gespeichert.");reset()}catch{setMsg("Speichern fehlgeschlagen.")}}
return <section className="sports-admin"><button className="admin-back" onClick={onBack}>← Zurück</button><header><p>TSU Ainet · Firestore</p><h2>Tabelle verwalten</h2><span>{rows.length} Tabellenzeilen</span></header><form onSubmit={submit} className="sports-form"><label>Mannschaft<select value={form.teamName} onChange={e=>setForm({...form,teamName:e.target.value})}>{TEAMS.map(t=><option key={t}>{t}</option>)}</select></label><label>Bewerb<input value={form.competitionName} onChange={e=>setForm({...form,competitionName:e.target.value})}/></label><label>Platz<input type="number" min="1" value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/></label><label>Verein<input value={form.clubName} onChange={e=>setForm({...form,clubName:e.target.value})}/></label>{[["Spiele","played"],["Siege","won"],["Unentschieden","drawn"],["Niederlagen","lost"],["Tore","goalsFor"],["Gegentore","goalsAgainst"],["Punkte","points"]].map(([label,key])=><label key={key}>{label}<input type="number" min="0" value={form[key as keyof typeof form] as string} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<div className="form-actions"><button>{editing?"Änderungen speichern":"Zeile anlegen"}</button>{editing&&<button type="button" className="secondary" onClick={reset}>Abbrechen</button>}</div></form>{msg&&<p className="admin-message">{msg}</p>}<div className="admin-list">{rows.map(r=><article key={r.id}><b>{r.position}.</b><div><small>{r.teamName} · {r.competitionName}</small><strong>{r.clubName}</strong><span>{r.played} Sp. · {r.goalsFor}:{r.goalsAgainst} · {r.points} Pkt.</span></div><button onClick={()=>edit(r)}>Bearbeiten</button><button className="danger" onClick={()=>confirm("Zeile wirklich löschen?")&&deleteDoc(doc(db,"kfvStandings",r.id))}>Löschen</button></article>)}</div></section>}
